/**
 * =============================================================
 * src/models/Complaint.ts – Complaint Mongoose Model
 * =============================================================
 * Central data model for civic issue reports.
 * Used by ALL 13 AI features and every major controller.
 *
 * FEATURES IMPLEMENTED:
 *  - Feature #1: category enum + aiAnalysis sub-document stores Roboflow detections
 *  - Feature #2: fake detection result stored in aiAnalysis.fakeScore
 *  - Feature #3: severityScore 0-100 computed by AI engine
 *  - Feature #4: used in heatmap aggregation pipeline
 *  - Feature #5: workerId assignment + worker skill matching
 *  - Feature #8: beforePhotoUrl + afterPhotoUrl for resolution verification
 *  - Feature #9: confirmations counter incremented by community validation
 *  - Feature #13: anomaly detection queries this collection
 *  - 2dsphere index on location enables MongoDB geo queries ($geoWithin, $nearSphere)
 * =============================================================
 */

import mongoose, { Document, Schema, Model } from 'mongoose';

// ---- Sub-types for AI Analysis ----
export interface IDetection {
  class: string;        // e.g. "pothole", "garbage_bag"
  confidence: number;   // 0.0 – 1.0 from Roboflow
  x: number;            // bounding box center x (px)
  y: number;
  width: number;
  height: number;
}

export interface IAIAnalysis {
  detections: IDetection[];       // Roboflow raw detections array
  description: string;            // Groq natural language description
  confidence: number;             // Overall AI confidence 0-100
  fakeScore: number;              // HuggingFace deepfake score 0-100 (Feature #2)
  severityFactors: string[];      // Human-readable factors used for score
  weatherImpact: boolean;         // True if weather (rain) multiplied score (Feature #4)
}

// ---- Main Complaint Interface ----
export interface IComplaint extends Document {
  _id: mongoose.Types.ObjectId;
  reportedBy: mongoose.Types.ObjectId;  // ref: User
  title: string;
  description: string;
  // category: auto-detected by Roboflow + Groq (Feature #1)
  category: 'Pothole' | 'Garbage' | 'Broken Street Light' | 'Water Leakage' | 'Road Damage';
  photoUrl: string;           // URL to uploaded photo (Multer local or Cloudinary)
  // location: GeoJSON-compatible for $geoWithin / $nearSphere queries
  location: {
    lat: number;
    lng: number;
    address: string;          // Reverse-geocoded via Nominatim (Feature #1)
  };
  status: 'Pending' | 'Assigned' | 'InProgress' | 'Resolved';
  // severityScore: computed by Feature #3 AI Severity Engine
  // Factors: Roboflow detection size + Groq analysis + proximity to critical locations
  //          + complaint density in 200m radius last 30 days
  severityScore: number;
  aiAnalysis: IAIAnalysis;
  workerId: mongoose.Types.ObjectId | null;    // Assigned via Feature #5
  // confirmations: incremented each time a nearby citizen confirms (Feature #9)
  confirmations: number;
  // Before/after photos for AI resolution verification (Feature #8)
  beforePhotoUrl: string;
  afterPhotoUrl: string;
  // Tags: auto-generated by Groq for search/filter
  tags: string[];
  // aiSummaryTranslated: Groq Tamil translation cached (Feature #10)
  aiSummaryTranslated: string;
  createdAt: Date;
  updatedAt: Date;
}

// ---- Schema Definition ----
const ComplaintSchema = new Schema<IComplaint>(
  {
    reportedBy: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },

    title: {
      type: String,
      required: [true, 'Title is required'],
      trim: true,
      maxlength: [200, 'Title cannot exceed 200 characters'],
    },

    description: {
      type: String,
      required: [true, 'Description is required'],
      trim: true,
      maxlength: [2000, 'Description cannot exceed 2000 characters'],
    },

    // Category set initially from form, then overridden by Roboflow + Groq (Feature #1)
    category: {
      type: String,
      enum: ['Pothole', 'Garbage', 'Broken Street Light', 'Water Leakage', 'Road Damage'],
      required: true,
    },

    photoUrl: {
      type: String,
      required: [true, 'Photo is required for AI analysis'],
    },

    // location.coordinates stored as [lng, lat] for GeoJSON compatibility
    // But we also store lat/lng separately for easy JS access
    location: {
      lat: { type: Number, required: true },
      lng: { type: Number, required: true },
      address: { type: String, default: '' }, // Populated by Nominatim reverse geocoding
    },

    status: {
      type: String,
      enum: ['Pending', 'Assigned', 'InProgress', 'Resolved'],
      default: 'Pending',
    },

    // severityScore: 0-100. Used for:
    //   - Admin dashboard ordering (highest severity first)
    //   - Heatmap intensity weighting (Feature #4)
    //   - Weather multiplier (rain → score × 3, capped at 100) (Feature #4)
    severityScore: {
      type: Number,
      default: 0,
      min: 0,
      max: 100,
    },

    // aiAnalysis: Full AI pipeline result stored for transparency + re-use
    aiAnalysis: {
      detections: [
        {
          class: String,
          confidence: Number,
          x: Number,
          y: Number,
          width: Number,
          height: Number,
        },
      ],
      description: { type: String, default: '' },
      confidence: { type: Number, default: 0 },
      fakeScore: { type: Number, default: 0 },       // Feature #2
      severityFactors: [String],                      // Feature #3
      weatherImpact: { type: Boolean, default: false }, // Feature #4
    },

    // workerId: set by Feature #5 smart worker assignment
    workerId: {
      type: Schema.Types.ObjectId,
      ref: 'Worker',
      default: null,
    },

    // confirmations: Feature #9 community validation counter
    confirmations: {
      type: Number,
      default: 0,
      min: 0,
    },

    // Photo pair for AI resolution verification (Feature #8)
    beforePhotoUrl: { type: String, default: '' },
    afterPhotoUrl: { type: String, default: '' },

    // Groq-generated tags for filtering/search
    tags: [{ type: String }],

    // Tamil translation of AI description (Feature #10)
    aiSummaryTranslated: { type: String, default: '' },
  },
  {
    timestamps: true,
    toJSON: {
      virtuals: true,
      transform: (_doc, ret) => {
        delete (ret as any).__v;
        return ret;
      },
    },
  }
);

// ---- Indexes ----

// Compound index for heatmap aggregation (Feature #4):
// Group by location within time window
ComplaintSchema.index({ 'location.lat': 1, 'location.lng': 1, createdAt: -1 });

// Severity descending – admin dashboard default sort
ComplaintSchema.index({ severityScore: -1 });

// Status index – worker assigned complaints query
ComplaintSchema.index({ status: 1 });

// ReportedBy – citizen "my complaints" query
ComplaintSchema.index({ reportedBy: 1, createdAt: -1 });

// WorkerId – worker assigned complaints query (Feature #5)
ComplaintSchema.index({ workerId: 1, status: 1 });

// Category index for filtering
ComplaintSchema.index({ category: 1 });

// ---- Model Export ----
const Complaint: Model<IComplaint> = mongoose.model<IComplaint>(
  'Complaint',
  ComplaintSchema
);
export default Complaint;
