/**
 * =============================================================
 * src/utils/pdfGenerator.ts – Weekly PDF Report Generator
 * =============================================================
 * Implements Feature #11: AI-Generated Weekly Summary PDF.
 *
 * Uses pdf-lib 1.17 to create a professional multi-page PDF
 * containing:
 *  - Cover page with city branding and date range
 *  - Executive summary from Groq AI (Feature #11)
 *  - Category breakdown table
 *  - Top 5 most severe complaints list
 *  - Resolution statistics section
 *  - Footer with generation timestamp
 *
 * Returns: PDF as Buffer (piped to HTTP response for download)
 * =============================================================
 */

import { PDFDocument, rgb, StandardFonts, PDFFont, PDFPage } from 'pdf-lib';

export interface WeeklyReportData {
  dateRange: string;                        // e.g., "Jan 01 – Jan 07, 2026"
  aiSummary: string;                        // Groq-generated executive summary
  stats: {
    total: number;
    resolved: number;
    pending: number;
    assigned: number;
    avgSeverity: number;
  };
  byCategory: Record<string, number>;       // { Pothole: 12, Garbage: 8, ... }
  topComplaints: Array<{                    // Top 5 by severity
    title: string;
    category: string;
    severity: number;
    status: string;
    address: string;
  }>;
  topAreas: string[];                       // Top 3 affected areas by name
}

// ---- Color constants (Chennai city branding palette) ----
const COLORS = {
  primary: rgb(0.1, 0.3, 0.7),      // Deep blue
  secondary: rgb(0.9, 0.4, 0.1),    // Orange accent
  success: rgb(0.1, 0.6, 0.3),      // Green
  danger: rgb(0.8, 0.1, 0.1),       // Red
  light: rgb(0.95, 0.95, 0.97),     // Light grey background
  dark: rgb(0.15, 0.15, 0.2),       // Dark text
  white: rgb(1, 1, 1),
  grey: rgb(0.5, 0.5, 0.55),
};

/**
 * generateWeeklyPDF – Creates the full weekly report PDF.
 * Each section is drawn using pdf-lib's low-level drawing API.
 *
 * @param data – Aggregated report data from adminController
 * @returns Buffer containing the complete PDF binary
 */
export async function generateWeeklyPDF(data: WeeklyReportData): Promise<Buffer> {
  // ---- Initialize PDF document ----
  const pdfDoc = await PDFDocument.create();
  const helvetica = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const helveticaBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  // =========================================================
  // PAGE 1: Cover + Executive Summary
  // =========================================================
  const page1 = pdfDoc.addPage([595, 842]); // A4 dimensions in points

  drawCoverPage(page1, data, helvetica, helveticaBold);

  // =========================================================
  // PAGE 2: Statistics + Category Breakdown + Top Complaints
  // =========================================================
  const page2 = pdfDoc.addPage([595, 842]);

  drawStatisticsPage(page2, data, helvetica, helveticaBold);

  // =========================================================
  // Save and return as Buffer
  // =========================================================
  const pdfBytes = await pdfDoc.save();
  return Buffer.from(pdfBytes);
}

// ---- Helper: Draw Cover Page ----
function drawCoverPage(
  page: PDFPage,
  data: WeeklyReportData,
  regular: PDFFont,
  bold: PDFFont
): void {
  const { width, height } = page.getSize();

  // ---- Header banner ----
  page.drawRectangle({
    x: 0,
    y: height - 120,
    width,
    height: 120,
    color: COLORS.primary,
  });

  // ---- Title text ----
  page.drawText('AI-SmartCivic', {
    x: 40,
    y: height - 60,
    size: 32,
    font: bold,
    color: COLORS.white,
  });

  page.drawText('Weekly Civic Intelligence Report', {
    x: 40,
    y: height - 90,
    size: 16,
    font: regular,
    color: rgb(0.8, 0.9, 1),
  });

  // ---- Date range badge ----
  page.drawRectangle({
    x: 40,
    y: height - 160,
    width: 250,
    height: 32,
    color: COLORS.secondary,
  });

  page.drawText(`📅 ${data.dateRange}`, {
    x: 52,
    y: height - 149,
    size: 13,
    font: bold,
    color: COLORS.white,
  });

  // ---- Generated by AI badge ----
  page.drawText(`Generated by Groq AI (${process.env.GROQ_MODEL || 'llama-3.3-70b-versatile'})`, {
    x: 40,
    y: height - 185,
    size: 9,
    font: regular,
    color: COLORS.grey,
  });

  // ---- Section: AI Executive Summary ----
  page.drawText('Executive Summary', {
    x: 40,
    y: height - 225,
    size: 16,
    font: bold,
    color: COLORS.primary,
  });

  // Draw horizontal rule under title
  page.drawLine({
    start: { x: 40, y: height - 232 },
    end: { x: width - 40, y: height - 232 },
    thickness: 1,
    color: COLORS.primary,
  });

  // ---- Word-wrapped AI summary text ----
  const summaryLines = wrapText(data.aiSummary, 90);
  let yPos = height - 255;

  for (const line of summaryLines.slice(0, 20)) { // Limit to 20 lines
    if (yPos < 200) break;
    page.drawText(line, {
      x: 40,
      y: yPos,
      size: 11,
      font: regular,
      color: COLORS.dark,
    });
    yPos -= 18;
  }

  // ---- Quick stats row ----
  const statsY = 120;
  const statItems = [
    { label: 'Total Reports', value: String(data.stats.total), color: COLORS.primary },
    { label: 'Resolved', value: String(data.stats.resolved), color: COLORS.success },
    { label: 'Pending', value: String(data.stats.pending), color: COLORS.secondary },
    { label: 'Avg Severity', value: `${data.stats.avgSeverity}/100`, color: COLORS.danger },
  ];

  statItems.forEach((stat, i) => {
    const x = 40 + i * 130;
    // Card background
    page.drawRectangle({ x, y: statsY - 10, width: 120, height: 60, color: COLORS.light });
    // Value
    page.drawText(stat.value, { x: x + 10, y: statsY + 25, size: 20, font: bold, color: stat.color });
    // Label
    page.drawText(stat.label, { x: x + 10, y: statsY + 8, size: 9, font: regular, color: COLORS.grey });
  });

  // ---- Footer ----
  page.drawText(
    `Chennai Smart City Initiative | Generated: ${new Date().toLocaleString('en-IN')}`,
    { x: 40, y: 30, size: 8, font: regular, color: COLORS.grey }
  );
  page.drawText('Page 1 of 2', { x: width - 80, y: 30, size: 8, font: regular, color: COLORS.grey });
}

// ---- Helper: Draw Statistics Page ----
function drawStatisticsPage(
  page: PDFPage,
  data: WeeklyReportData,
  regular: PDFFont,
  bold: PDFFont
): void {
  const { width, height } = page.getSize();

  // ---- Page header ----
  page.drawRectangle({ x: 0, y: height - 50, width, height: 50, color: COLORS.primary });
  page.drawText('Detailed Statistics', {
    x: 40, y: height - 32, size: 16, font: bold, color: COLORS.white,
  });
  page.drawText(data.dateRange, {
    x: width - 200, y: height - 32, size: 10, font: regular, color: rgb(0.8, 0.9, 1),
  });

  // ---- Category Breakdown Table ----
  let yPos = height - 80;

  page.drawText('Complaints by Category', { x: 40, y: yPos, size: 14, font: bold, color: COLORS.primary });
  yPos -= 25;

  // Table header
  page.drawRectangle({ x: 40, y: yPos - 5, width: 300, height: 22, color: COLORS.primary });
  page.drawText('Category', { x: 50, y: yPos + 2, size: 10, font: bold, color: COLORS.white });
  page.drawText('Count', { x: 220, y: yPos + 2, size: 10, font: bold, color: COLORS.white });
  page.drawText('% of Total', { x: 270, y: yPos + 2, size: 10, font: bold, color: COLORS.white });
  yPos -= 22;

  const categoryEntries = Object.entries(data.byCategory);
  categoryEntries.forEach(([cat, count], i) => {
    const rowBg = i % 2 === 0 ? COLORS.light : COLORS.white;
    page.drawRectangle({ x: 40, y: yPos - 5, width: 300, height: 20, color: rowBg });
    page.drawText(cat, { x: 50, y: yPos, size: 10, font: regular, color: COLORS.dark });
    page.drawText(String(count), { x: 230, y: yPos, size: 10, font: bold, color: COLORS.primary });
    const pct = data.stats.total > 0 ? ((count / data.stats.total) * 100).toFixed(1) : '0';
    page.drawText(`${pct}%`, { x: 275, y: yPos, size: 10, font: regular, color: COLORS.grey });

    // Simple bar chart inline
    const barWidth = (count / Math.max(...categoryEntries.map(([, c]) => c))) * 150;
    page.drawRectangle({ x: 350, y: yPos, width: barWidth, height: 12, color: COLORS.secondary });

    yPos -= 22;
  });

  // ---- Top Complaints ----
  yPos -= 20;
  page.drawText('Top 5 High-Severity Complaints', { x: 40, y: yPos, size: 14, font: bold, color: COLORS.primary });
  yPos -= 25;

  data.topComplaints.slice(0, 5).forEach((c, i) => {
    const severityColor = c.severity > 70 ? COLORS.danger : c.severity > 40 ? COLORS.secondary : COLORS.success;
    page.drawText(`${i + 1}. ${c.title.slice(0, 45)}`, { x: 40, y: yPos, size: 10, font: bold, color: COLORS.dark });
    page.drawText(`Severity: ${c.severity}/100`, { x: 370, y: yPos, size: 9, font: bold, color: severityColor });
    yPos -= 16;
    page.drawText(`   ${c.category} | ${c.status} | ${c.address.slice(0, 50)}`, {
      x: 40, y: yPos, size: 9, font: regular, color: COLORS.grey,
    });
    yPos -= 20;
  });

  // ---- Resolution Rate Progress Bar ----
  yPos -= 20;
  const resRate = data.stats.total > 0
    ? Math.round((data.stats.resolved / data.stats.total) * 100)
    : 0;

  page.drawText(`Resolution Rate: ${resRate}%`, { x: 40, y: yPos, size: 13, font: bold, color: COLORS.primary });
  yPos -= 20;

  const barBgWidth = width - 80;
  page.drawRectangle({ x: 40, y: yPos, width: barBgWidth, height: 16, color: COLORS.light });
  page.drawRectangle({
    x: 40, y: yPos, width: (resRate / 100) * barBgWidth, height: 16,
    color: resRate > 70 ? COLORS.success : COLORS.secondary,
  });

  // ---- Footer ----
  page.drawText(
    `Chennai Smart City Initiative | AI-SmartCivic Platform`,
    { x: 40, y: 30, size: 8, font: regular, color: COLORS.grey }
  );
  page.drawText('Page 2 of 2', { x: width - 80, y: 30, size: 8, font: regular, color: COLORS.grey });
}

// ---- Utility: Word wrap text for pdf-lib ----
// pdf-lib does not support automatic word wrapping; we do it manually.
function wrapText(text: string, maxCharsPerLine: number): string[] {
  const words = text.split(' ');
  const lines: string[] = [];
  let current = '';

  for (const word of words) {
    if ((current + ' ' + word).trim().length <= maxCharsPerLine) {
      current = (current + ' ' + word).trim();
    } else {
      if (current) lines.push(current);
      current = word;
    }
  }
  if (current) lines.push(current);

  return lines;
}
